### ISSUE TITLE
arabic support

### ISSUE THREAD

**Issue by abuali129** [Atvaark/FoxEngine.TranslationTool#1]
as it mentioned the arabic should use UTF-8 Encoding
but when I try to do it that way after repacking I get question marks instead of the letter I wrote in arabic.

I unpack .subp
edited .xml 
repack the .subp using the .xml
unpack .subp again to double check 
all thing I translated is shown as ??????? ???? ??? ????

**Comment by Atvaark** [comment]
If I remember correctly picking Arabic as the subtitle language isn't officialy supported by the game. There are Arabic bitmap fonts in the archives, but since you can't pick Arabic in the menu the game will continue with the Latin bitmap and fail to look up the Arabic glyphs/characters.
What could work is replacing the Latin font files with the Arabic ones.

**Comment by abuali129** [comment]
yes that right, but I didn't even came to that phase, I'm still on editing .subp but with no luck

**Comment by abuali129** [comment]
this is after editing xml
http://i.imgur.com/HlzP1Ej.png

this is after repacking .subp and unpack it for double check
http://i.imgur.com/c3r3UHC.png

the characters encoding in xml is not supported by SubpTool? is that the case?
I tried punch of different encoding but all leads to same result

I will take a look on how PES 2015 arabic files coding looks like, it uses fox engine too

**Comment by Atvaark** [comment]
[FoxEngine.TranslationTool v0.1.3](https://github.com/Atvaark/FoxEngine.TranslationTool/releases/tag/v0.1.3) should use the encoding specified by the language option (-ara in your case) instead of of the ANSI codepage of your system.

That should fix your issue.
